{% set version = "2020.6.1" %}

package:
  name: l18n
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/l18n/l18n-{{ version }}.tar.gz
  sha256: ea7a65b2f0935b14601a3295f2c5e5e8b54126dd1e6a7fef4e44d2b8dd5b695a

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  host:
    - python
    - pip
    - pytz >=2016.6
    - six
  run:
    - python
    - pytz >=2016.6
    - six

test:
  imports:
    - l18n

about:
  home: https://bitbucket.org/tkhyn/l18n
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Internationalization for pytz timezones and territories

extra:
  recipe-maintainers:
    - ocefpaf
