{% set version = "2020.6" %}

package:
  name: l18n
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/l18n/l18n-{{ version }}.tar.gz
  sha256: b8f5a724a00a6b06ffbf568173e8e03cc5aff35a51c0c9a12eb0c80cb004a062

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  host:
    - python
    - pip
    - pytz >=2016.6
    - six
  run:
    - python
    - pytz >=2016.6
    - six

test:
  imports:
    - l18n

about:
  home: https://bitbucket.org/tkhyn/l18n
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Internationalization for pytz timezones and territories

extra:
  recipe-maintainers:
    - ocefpaf
