{% set name = "l18n" %}
{% set version = "2021.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/l18n-{{ version }}.tar.gz
  sha256: 1956e890d673d17135cc20913253c154f6bc1c00266c22b7d503cc1a5a42d848

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pytz >=2020.1
    - six

test:
  imports:
    - l18n
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tkhyn/l18n
  summary: Internationalization for pytz timezones and territories
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
